### ISSUE TITLE
off topic 

### ISSUE THREAD

**Issue by tcpipchip** [Chreece/FaceRec_BTHome#1]
Sir, about your module Recognizer

let me see if i understand, this HLK-TX510 returns a code for each face that detecs ? if i point the camera to 300.000 different persons, willi get 300.000 differents IDs ? This ID is transmitted to the serial...and i can transmit for my Database, right (for searching). Never i will have repeated ID, right ?

My idea is to distribuite the HLK-TX510 in 1500 points...and just get the ID face of each one of this 300.000 in a big database.

I mean, a pacient goes on HLK-TX510 camera, then the HLK-TX510 must to return ID (no need detects if the pacient is JOHN, MARY, CARY,etc), only need to returns a ID that is unique for that person (pacient)

**Comment by Chreece** [comment]
The code just translates the serial messages from the firmware of TX510 to BTHome entities. 
The module as mentioned in the docs can register up to 1000 faces (not 300.000). So in theory it can recognize up to 1000 different persons.
The user ID  that returned after a successful recognition is  the ascending number that the face got in the internal database of the module when it was registered. 
All of this has nothing to do with the repo. This code is just a "translator" between the firmware of the TX510 and the BTHome protocol.

**Comment by tcpipchip** [comment]
Thank you! I aborted this hardware. I am doing using raspberry and amazon recognizer. Getting progress!

**Comment by Chreece** [comment]
You could also do that with [Compreface](https://github.com/exadel-inc/CompreFace).
The TX510 is developed mainly for local applications...

**Comment by tcpipchip** [comment]
hi @Chreece
WOW! I will read now about this COMPREFACE
Thanks!

**Comment by tcpipchip** [comment]
wow! That´s is cool!

**Comment by tcpipchip** [comment]
thanks again!
