### ISSUE TITLE
Firmware - upgrade to english version ...

### ISSUE THREAD

**Issue by pploume** [Chreece/FaceRec_BTHome#2]
Hi,
Thanks for your work ...

I've tryied to upload the ENglish firmware you provide but I get an error (in chinese ...)

I assume (hlk_tx510.exe V1.0.3 --> Query version) 
the installed chinese version is 1.00.0011
and
the version here is 1.00.0006, meaning an earlier one

You know where to find the 1.00.0011 ENGLISH version ?
Cant't find it on HLK website ... and the support seems to be 'light' for this product

Thanks in advance
p

BTW : is you know also how to grab an .EXE in english ...

**Comment by Chreece** [comment]
You could try and communicate with hlk in AliExpress, they are always happy to help.
